- headers:
    user-agent: fetch-synthetic-monitor
  method: GET
  name: fetch index page
  url: https://fetch.com/

- headers:
    user-agent: fetch-synthetic-monitor
  method: GET
  name: fetch careers page
  url: https://fetch.com/careers

- body: '{"foo":"bar"}'
  headers:
    content-type: application/json
    user-agent: fetch-synthetic-monitor
  method: POST
  name: fetch some fake post endpoint
  url: https://fetch.com/some/post/endpoint

- name: fetch rewards index page
  url: https://www.fetchrewards.com/


#- method: GET
#  name: fetch index page
#  url: https://fetch.com/
#
#- method: POST
#  name: fetch post page
#  url: https://fetch.com/post
#  headers:
#    content-type: application/json
#  body: '{"foo": "bar"}'
